version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
    timezone: Australia/Melbourne
  reviewers:
  - MrJacz
  assignees:
  - MrJacz
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.29
    - 14.14.31
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
  - dependency-name: lodash
    versions:
    - 4.17.20
